root = "./"
skynet = root.."skynet/"
thread = 8
logger = nil
logpath = "."
harbor = 1
address = "127.0.0.1:2526"
master = "127.0.0.1:2013"
start = "test_base_main"	-- main script
bootstrap = "snlua bootstrap"	-- The service for bootstrap
standalone = "0.0.0.0:2013"
luaservice = root.."test/?.lua;"..skynet.."service/?.lua;"..skynet.."test/?.lua;"..skynet.."examples/?.lua"
lualoader = skynet .. "lualib/loader.lua"
lua_path = root.."lualib/?.lua;"..skynet.."lualib/?.lua;"..skynet.."lualib/?/init.lua"
lua_cpath = skynet .. "luaclib/?.so"
-- preload = "./examples/preload.lua"	-- run preload.lua before every lua service run
cpath = skynet.."cservice/?.so"
-- daemon = "./skynet.pid"
